version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "6432:5432"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  mariadb:
    image: mariadb:11.1.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
