version: "3.9"
services:
  postgres:
    image: postgres:16.1
    command: ["postgres", "-c", "fsync=off", "-c", "max_connections=5000", "-c", "shared_buffers=250MB"]
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  mariadb:
    image: mariadb:11.1.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
