version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
  migration-postgres:
    image: ghcr.io/emilpriver/geni:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./migrations:/migrations
    command: up
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
  migration-mysql:
    image: ghcr.io/emilpriver/geni:latest
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/development
    volumes:
      - ./migrations:/migrations
    command: up
  mariadb:
    image: mariadb:11.1.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  migration-mariadb:
    image: ghcr.io/emilpriver/geni:latest
    environment:
      - DATABASE_URL=mariadb://user:password@mariadb:3306/development
    volumes:
      - ./migrations:/migrations
    command: up
